### ISSUE TITLE
Improve configurations documentation for setup of homeserver

### ISSUE THREAD

**Issue by frlan** [matrix-org/matrix-hookshot#238]
**Is your feature request related to a problem? Please describe.**
For startes it's not clear how in detail to configure the service. E.g. 

```
bridge:
  # Basic homeserver configuration
  #
  domain: example.com
  url: http://localhost:8008
  mediaUrl: http://example.com
  port: 9993
  bindAddress: 127.0.0.1
```

does this relate to an existing homeserver or is this a homeserver the hookshot is setting up

**Describe the solution you'd like**

Be more verbose and maybe even state some of the obvious things
