### ISSUE TITLE
Connecting to a GitLab Project via Command Fails with "Cannot read properties of undefined"

### ISSUE THREAD

**Issue by Eisfunke** [matrix-org/matrix-hookshot#393]
**Describe the bug**

Connecting a room fails. The bot sends "Failed to handle command." and in the log this appears:

```
WARN 11:07:36:827 [CommandConnection] Failed to handle command: Cannot read properties of undefined (reading 'filter')
```

**To Reproduce**

1. Create a room
2. Invite Hookshot Bot
3. Send !hookshot gitlab project URL

**Expected behavior**
The room is connected.

I'm running the latest Docker image, with this config:

```
gitlab:
  instances:
    ALIAS:
      url: GITURL
  webhook:
    secret: SECRET
    publicUrl: WEBHOOKURL
  userIdPrefix: _gitlab_
```

This seems to be the same problem referenced here: https://github.com/matrix-org/matrix-hookshot/issues/361#issuecomment-1139104748

I'm opening a new issue as that one is closed.
