### ISSUE TITLE
Allow creation of "service bots" which can be used for specific service(s)

### ISSUE THREAD

**Issue by Half-Shot** [matrix-org/matrix-hookshot#436]
E.g. In the config you could specify you would like to have a JIRA bot that allows users to invite it to rooms in order to bridge JIRA things, without necessarily including all the other services too.

I'd probably advise having a new config for this like:

```yml
service_bots:
    - localpart: jira
      displayname: Jira
      avatar_url: mxc://jira
      services: [jira]
```

The bots could also create a widget for one specific type of configuration when prompted, which is issue https://github.com/matrix-org/matrix-hookshot/issues/437.
