### ISSUE TITLE
Maybe bug: config `widgets.publicUrl` remains unset

### ISSUE THREAD

**Issue by ja0nz** [matrix-org/matrix-hookshot#550]
I experience issues while setting up widgets. No matter which URL I set in `widgets.publicUrl` as far as I can see from DevTools>Network & DevTools>Console there is no call issued. Requests issued at:
> http:// + `bridge.domain` + /widgetapi/v1/static/

This is especially problematic as I have enfored HTTPS set on my reverse proxy. And the `http://` request results in an fetching error
> Refusing to load mixed-content app: https: http: 
> http://matrix.domain.tld/widgetapi/v1/static/#/?kind=roomConfig&roomId=$matrix_room_id&widgetId=$matrix_widget_id

without widget to load consequently.

So I wonder if I got something wrong here? Otherwise, webhooks are working fine for me. I will conclude this question/bug report with the config sections in question. Thanks

```
bridge:
  domain: matrix.domain.tld
  url: http://conduit:6167 
  port: 9993
  bindAddress: 0.0.0.0

widgets:
  addToAdminRooms: false
  roomSetupWidget:
    addOnInvite: false
  publicUrl: https://matrix.domain.tld/widgetapi/v1/static/ # <- No observable effect, no matter which value I set here
  branding:
    widgetTitle: Hookshot Configuration
  #openIdOverrides:
  #  my-local-server: "http://conduit:6167"
```

**Comment by jaller94** [comment]
# Relevant code

Where `widget.publicUrl` is "validated":
https://github.com/matrix-org/matrix-hookshot/blob/bf66dd2a012c8791f147e2c49dd91403a57043bc/src/Config/Config.ts#L299-L304

Where the widget is set:
https://github.com/matrix-org/matrix-hookshot/blob/28235547d2b3abed43f8a626227e3b7fa5afa55d/src/Widgets/SetupWidget.ts#L61

**Comment by AndrewFerr** [comment]
If `matrix.domain.tld` is a placeholder for your Matrix homeserver domain, that explains the problem: **`widgets.publicUrl` must be set to the URL of your widgets webpage**, not your Matrix homeserver.  Using your homeserver URL won't work unless your proxy is redirecting traffic for `/widgetapi` to your Hookshot installation.

You must also set the `listeners` section with at least one entry that specifies a `widgets` resource, like so:
```
listeners:
  - port: 9002
    bindAddress: 127.0.0.1
    resources:
      - widgets
```

Summary of network interactions:

```
World   |  Your public-facing endpoints |                                     |  Private endpoints on your machine
Browser -> https://${widgets.publicUrl} -> Your reverse proxy / load balancer -> http://${listeners[*].bindAddress}:${listeners[*].port}
```
where `listeners[*]` is every entry of `listeners` that includes `widgets` in its `resources` section.

Closing this case because the widget URL setting is known to work, as it is functional on live deployments.  If you still need configuration help, feel free to drop by the support room at [#hookshot:half-shot.uk](https://matrix.to/#/#hookshot:half-shot.uk).
