### ISSUE TITLE
Ability to declaratively manage webhooks for rooms

### ISSUE THREAD

**Issue by Arkaniad** [matrix-org/matrix-hookshot#636]
Semi related to #635 - if we could do this managing a unique webhook transform would be less complex

Right now we're stringing together AlertManager alerts from multiple clusters into multiple channels. Our current workflow per-cluster-channel is thus:

Per environment:
- In target alerting channel, invite hookshot bot
- Invoke hookshot widget configuration
- Create webhook, configure transform
- Configure environment's Alertmanager to send webhooks to the hook

This isn't a lot, but we are already having channels with ~5 webhooks each and if we have to update transforms it's laborious to do so to each and every one by hand. 

It would be splendid if we could do something like this:

``` yaml
bridge: { ... }
generic: { ... }
listeners: { ... }
logging: { ... }
metrics:
  enabled: true
passFile: /data/passkey.pem
widgets:
  addToAdminRooms: false
  branding:
    widgetTitle: Hookshot Configuration
  publicUrl: https://webhook-hookshot.infra.foo.host/widgetapi/v1/static
  roomSetupWidget:
    addOnInvite: false
  setRoomName: false
rooms:
  - address: "#alert-room:foo.host"
    requiresInvite: true
    configureWidgets: true # overriden by roomSetupWidget above?
    
    webhooks:
      - name: "Foo Alerts"
        type: generic
        id: 8399849d-2fd8-4f1f-bf38-471f220a15a3
        jsTransform:
          enabled: true
          inline: |-
            stuff.do(true);
          # alternatively / preferably so we can map via k8s configmaps
          # file: /path/to/transform.js

```
