### ISSUE TITLE
Ingress Example for Helm Chart

### ISSUE THREAD

**Issue by rhizoet** [matrix-org/matrix-hookshot#780]
Can you please create an example of a working ingress for the helm chart?

I tried to specify only the hosts. Unfortunately that did not work.

When I specify the following:
```YAML
hosts:
  - host: example.com
    paths:
      - path: /webhook
        pathType: Prefix
        backend:
          port:
            number: 9000
```
I get the error:
`Upgrade "hookshot" failed: failed to create resource: Ingress.extensions "hookshot-appservice" is invalid: spec.rules[0].http.paths[0].backend: Required value: port name or number is required`

So, could you please provide a working ingress example. I don't know how it should look like.

Thanks in advance.

**Comment by rhizoet** [comment]
@Arkaniad do you have any news on this?

**Comment by Arkaniad** [comment]
Nothing actioned yet - Some notes though:

A production ready ingress configuration with this chart looks like this:

``` yaml
ingress:
  webhook:
    enabled: true
    # className: "nginx-public"
    annotations: {}
    hosts:
      - host: webhook-hookshot.infra.test.dev
        paths:
          - path: /
            pathType: Prefix
            port: 9000
    tls:
    - secretName: monitoring-hookshot-webhook-tls
      hosts:
        - webhook-hookshot.infra.test.dev

  appservice:
    enabled: true
    # className: "nginx-public"
    annotations: {}
    hosts:
      - host: hookshot.infra.test.dev
        paths:
          - path: /
            pathType: Prefix
            port: 9002
    tls:
    - secretName: monitoring-hookshot-app-tls
      hosts:
        - hookshot.infra.test.dev
```

Ideally, the host port portion of the path should default to the configured service port but for now these just need to match manually.

For the AppService registration, the chart is configured to pass these through via `values.yaml` - we use [sops](https://github.com/mozilla/sops) w/ Helm so it's okay for us to have a separate encrypted values file with secrets in it. This is all [here](https://github.com/matrix-org/matrix-hookshot/blob/2173a8ccb9e28ace361d6168287ac3a807c26d85/helm/hookshot/values.yaml#L302) but I can see that I've overlooked adding a config for mounting externally managed secrets, so I'll get that added :)
